### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by cKlee** [gbv/lod303#1]
What's the purpose of this project? Does it solve a problem? Or is it just for internal use?

**Comment by nichtich** [comment]
It implements content negotiation via HTTP Accept header for the ontologies listed in the config file. As they are hosted at github.io, a resolver is needed. This is hosted at uri.gbv.de/ontology

On 3. Juli 2014 15:56:35 MESZ, Carsten Klee notifications@github.com wrote:

> What's the purpose of this project? Does it solve a problem? Or is it
> just for internal use?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/gbv/lod303/issues/1

## 

Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
